Page d'accueil
WildCodeSchool/2023-02-Orleans-Spe-P1-A pull request #14
Opened 2023-03-03 11:29 UTC by Richarddesnoues

2023-03-03 13:27 UTC, Chloebert requested changes

2023-03-03 13:27 UTC, Chloebert commented on assets/accueil.css
> +
ligne vide

2023-03-03 13:27 UTC, Chloebert commented on assets/accueil.css
> +
là aussi ligne vide :(

2023-03-03 13:27 UTC, Chloebert commented on assets/accueil.css
> +
ici

2023-03-03 13:27 UTC, Chloebert commented on assets/accueil.css
> +
et là

2023-03-03 13:27 UTC, Chloebert commented on assets/style.css
> +
et là beaucoup de lignes vides

2023-03-03 14:18 UTC, Alexis-Thibault commented on assets/home.css
> +
ligne vide

2023-03-03 14:18 UTC, Alexis-Thibault approved these changes

2023-03-03 15:06 UTC, Chloebert approved these changes

2023-03-03 15:12 UTC, YDrogen requested changes
- [x] taille des images (4mo une giraffe ?? 🐙 )

2023-03-03 15:12 UTC, YDrogen commented on assets/accueil.css
> +
oui

2023-03-03 15:12 UTC, YDrogen commented on assets/accueil.css
> +
👍

2023-03-03 15:12 UTC, YDrogen commented on assets/accueil.css
> +
👍

2023-03-03 15:12 UTC, YDrogen commented on assets/style.css
> +/*************************************FOOTER*************************************************/
encore des * :(

2023-03-03 15:12 UTC, YDrogen commented on assets/style.css
> +
👍

2023-03-03 15:12 UTC, YDrogen commented on components/footer.html
> +
ligne vide

2023-03-03 15:15 UTC, Richarddesnoues commented on assets/style.css
> +/*************************************FOOTER*************************************************/
je ne comprends rien je les ai tous virés la dernière fois

2023-03-04 15:04 UTC, Chloebert approved these changes

2023-03-04 18:00 UTC, YDrogen approved these changes

2023-03-04 18:00 UTC, merged