Dev to main
WildCodeSchool/2023-02-Orleans-Spe-P1-A pull request #16
Opened 2023-03-03 14:03 UTC by Chloebert

2023-03-03 14:06 UTC, Alexis-Thibault submitted a review, later dismissed

2023-03-06 09:51 UTC, Alexis-Thibault approved these changes, later dismissed

2023-03-06 09:55 UTC, YDrogen requested changes
image hero 2mb

2023-03-06 10:25 UTC, Alexis-Thibault submitted a review, later dismissed

2023-03-06 10:30 UTC, YDrogen requested changes
Encore plein de liens morts

2023-03-06 10:46 UTC, Richarddesnoues approved these changes

2023-03-06 10:47 UTC, YDrogen approved these changes

2023-03-06 10:47 UTC, merged